version: "3"
services:
  app:
    image: php:7.4-cli
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /var/www
    ports:
      - 50051:50051
      - 2112:2112
    volumes:
      - .:/var/www
#    entrypoint: sleep infinity
