<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: import/message.proto

namespace App\GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
˜
import/message.protoapp.message"
Message
msg (	"
Job
value (	"
JobID

id (	B(ÊApp\\Service\\MessageâApp\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

