<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace App\Calculator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.Add</code>
 */
class Add extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 num1 = 1;</code>
     */
    protected $num1 = 0;
    /**
     * Generated from protobuf field <code>int32 num2 = 2;</code>
     */
    protected $num2 = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $num1
     *     @type int $num2
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\Calculator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 num1 = 1;</code>
     * @return int
     */
    public function getNum1()
    {
        return $this->num1;
    }

    /**
     * Generated from protobuf field <code>int32 num1 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNum1($var)
    {
        GPBUtil::checkInt32($var);
        $this->num1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 num2 = 2;</code>
     * @return int
     */
    public function getNum2()
    {
        return $this->num2;
    }

    /**
     * Generated from protobuf field <code>int32 num2 = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNum2($var)
    {
        GPBUtil::checkInt32($var);
        $this->num2 = $var;

        return $this;
    }

}

